config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'admin/registrations',
    passwords: 'admin/passwords',
    sessions: 'admin/sessions',
    invitations: 'admin/invitations'
  }

  root 'home#index'

  scope :users, controller: 'admin/users' do
    get :edit_password
    patch :edit_password, to: :update_password
    get :delete_account
  end

  namespace :admin do
    root 'posts#index'
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable

  validates_uniqueness_of :email, case_sensitive: false

  validates_presence_of :first_name, :last_name, :email
end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    layout 'admin'
    before_action :authenticate_user!
  end
end

app/controllers/admin/invitations_controller.rb
module Admin
  class InvitationsController < Devise::InvitationsController
    layout 'admin'
  end
end

app/controllers/admin/passwords_controller.rb
module Admin
  class PasswordsController < Devise::PasswordsController
    layout 'session'

    prepend_before_filter :require_no_authentication, only: [:edit, :update]

    # GET /resource/password/new
    def new
      self.resource = current_user || resource_class.new
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::AdminController
  def index
  end
end

app/controllers/admin/registrations_controller.rb
module Admin
  class RegistrationsController < Devise::RegistrationsController
    layout 'admin'

    def new
      raise ActionController::RoutingError.new('Not Found')
    end

    def destroy
      if resource.valid_password?(params[:user][:password])
        resource.destroy
        Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
        render js: "window.location = '#{root_path}'"
      else
        resource.errors[:password] << 'Incorrect password'
        render 'admin/users/delete_account'
      end
    end

    protected

    def update_resource(resource, params)
      resource.update_without_password(params)
    end
  end
end

app/controllers/admin/sessions_controller.rb
module Admin
  class SessionsController < Devise::SessionsController
    layout 'session'
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::AdminController
    layout 'admin'

    before_action :load_user

    def edit_password
    end

    def update_password
      password = user_params[:password]
      password_confirmation = user_params[:password_confirmation]
      if @user.update_with_password(user_params) && password.present? && password == password_confirmation
        sign_in(@user, bypass: true)
        redirect_to admin_root_path
      else
        @user.errors[:password] << "can't be blank" if password.blank?
        @user.errors[:password_confirmation] << "doesn't match with Password" if password != password_confirmation
        render :edit_password
      end
    end

    def delete_account
      @user = current_user
    end

    private

    def user_params
      params.require(:user).permit(
        :first_name,
        :last_name,
        :email,
        :password,
        :password_confirmation,
        :current_password
      )
    end

    def load_user
      @user = current_user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update).concat [:first_name, :last_name]
    devise_parameter_sanitizer.for(:sign_up).concat [:first_name, :last_name]
    devise_parameter_sanitizer.for(:accept_invitation).concat [:first_name, :last_name]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/preview/home_controller.rb
module Preview
  class HomeController < PreviewController
    def index
    end
  end
end

app/controllers/preview/preview_controller.rb
module Preview
  class PreviewController < ApplicationController
    layout 'preview'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/posts/index.html.slim
p= link_to 'Logout', destroy_user_session_path, method: :delete
p= link_to 'Edit my account', edit_user_registration_path
p= link_to 'Invite', new_user_invitation_path

app/views/admin/posts/index.slim
p= link_to 'Logout', destroy_user_session_path, method: :delete
p= link_to 'Edit my account', edit_user_registration_path
p= link_to 'Invite', new_user_invitation_path
p= link_to 'Change password', edit_password_path

app/views/admin/shared/_modal.slim
.modal.fade
  .modal-dialog
    .modal-content
      .modal-header.clearfix
        button.close data-dismiss="modal"
          |&times;
        h4 Header
      .modal-body.clearfix

app/views/admin/users/_delete_account_body.slim
= simple_form_for(@user, url: registration_path(@user), method: :delete, remote: true) do |f|
  = f.input :password, autofocus: true, label: "Password (#{link_to('Forgot your password?', new_user_password_path)})".html_safe
  = f.button :submit, 'Confirm password', class: 'btn-primary'

app/views/admin/users/delete_account.js.erb
renderModal(
  "<%= j render 'admin/shared/modal' %>",
  'delete-account-modal',
  'Confirm password to continue',
  "<%= j render 'admin/users/delete_account_body' %>"
);

app/views/admin/users/edit_password.slim
.col-xs-10.col-sm-8.col-md-6.col-lg-6.col-xs-offset-1.col-sm-offset-2.col-md-offset-3.col-lg-offset-3
  .login-panel.panel.panel-default.well
    .panel-heading
      h3 Change password
    .panel-body
      = simple_form_for(@user, url: edit_password_path, method: :patch) do |f|
          = f.hidden_field :first_name
          = f.hidden_field :last_name
          = f.hidden_field :email
          = f.input :password, label: 'New password', autofocus: true
          = f.input :password_confirmation, label: 'New password (confirm)'
          = f.input :current_password, label: "Old password (#{link_to('Forgot your password?', new_user_password_path)})".html_safe
          = f.submit 'Change password', name: :password, class: 'btn btn-primary'
          = link_to 'Cancel', admin_root_path, class: 'btn'

app/views/home/index.html.slim
.cover
.container
  h1.logo Herman Zvonimir Došilović

.content
  .social
    = iconfont_linkedin link: 'https://www.linkedin.com/in/hermanzdosilovic', round: true, input_html: { target: '_blank' }
    = iconfont_facebook link: 'https://www.facebook.com/profile.php?id=1203852653', round: true, input_html: { target: '_blank' }
    = iconfont_github link: 'https://github.com/hermanzdosilovic', round: true, input_html: { target: '_blank' }
    = iconfont_bitbucket link: 'https://bitbucket.org/hermanzdosilovic/', round: true, input_html: { target: '_blank' }
    = iconfont_mail link: 'mailto:hermanz.dosilovic@gmail.com', round: true
    = iconfont_document link: 'https://dl.dropboxusercontent.com/u/96682413/Herman_Zvonimir_Dosilovic_Resume.pdf', round: true, input_html: { target: '_blank' }
  .motto
    h4.info-text Site under construction

app/views/home/index.slim
.greeting.random-wallpaper#home
  .cover class=['blue', 'red', 'black', 'orange', 'green'].sample
    .container
      = image_tag asset_path('me.jpg'), class: 'img-circle', id: 'me'
      h1#name Herman Zvonimir Došilović
      hr.small
      p#about
        | Computer Science student at&nbsp
        = link_to 'FER', 'http://www.fer.unizg.hr/', target: '_blank'
        |&nbspand Software Engineer, Intern at&nbsp
        = link_to 'Vibby', 'https://www.vibby.com/', target: '_blank'

.contact#contact
  .container
    h1 Contact me
    .social
      .social-group
        = iconfont 'zocial-linkedin', size: 150, link: 'http://bit.ly/herman-linkedin', background: '#1b85b7', foreground: '#fbfbfb', round: true, input_html: { target: '_blank' }
        = iconfont 'fontawesome-facebook', size: 150, link: 'http://bit.ly/herman-facebook', background: '#3b5999', foreground: '#fbfbfb', round: true, input_html: { target: '_blank' }
      .social-group
        = iconfont 'fontawesome-github', size: 150, link: 'http://bit.ly/herman-github', background: '#313131', foreground: '#fbfbfb', round: true, input_html: { target: '_blank' }
        = iconfont 'zocial-bitbucket', size: 150, link: 'http://bit.ly/herman-bitbucket', background: '#205081', foreground: '#fbfbfb', round: true, input_html: { target: '_blank' }
      .social-group
        = iconfont 'zocial-email', size: 150, link: 'mailto:hermanz (tocka) dosilovic (pri) gmail (tocka) com', background: '#d2382e', foreground: '#fbfbfb', round: true, input_html: { id: 'mail' }
        = iconfont 'entypo-doc-text', size: 150, link: 'http://bit.ly/herman-cv', background: '#e29024', foreground: '#fbfbfb', round: true, input_html: { target: '_blank' }

app/views/layouts/_footer.html.slim
| © 2016 Herman Zvonimir Došilović

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default.navbar-fixed-top.transparent.transition
  .container-fluid
    .navbar-header
      = button_tag class: 'navbar-toggle', 'data-toggle': 'collapse',  'data-target': "#navbar-collapse-1" do

        span.sr-only
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Welcome', '#home', class: 'scroll navbar-brand visible-xs-inline-block'
      = link_to 'Welcome', '#home', class: 'scroll navbar-brand hidden-xs'
    .collapse.navbar-collapse#navbar-collapse-1
      ul.nav.navbar-nav.navbar-left
        li.hidden
          = link_to 'Home', '#home', class: 'scroll'
        li
          = link_to 'Contact', '#contact', class: 'scroll'

app/views/layouts/admin.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Web
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    .container
      = yield

app/views/layouts/application.html.slim
doctype html
<!-- Almost everything I do is open source. The same goes for this site. -->
<!-- Go ahead and grab the source here: https://github.com/hermanzdosilovic/web -->

html
  head
  meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
  title Herman Zvonimir Došilović

  = favicon_link_tag 'favicon.ico'
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'application'

  meta{name='viewport', content='width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no'}

  = csrf_meta_tags

  body
    .site
      .navigation
        = render 'layouts/navigation'
      .content
        = yield
      .footer
        = render 'layouts/footer'

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Web
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body
    .container
      = yield

app/views/layouts/session.html.slim
doctype html
<!-- Almost everything I do is open source. The same goes for this site. -->
<!-- Go ahead and grab the source here: https://github.com/hermanzdosilovic/web -->

html
  head
  meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
  title Herman Zvonimir Došilović

  = favicon_link_tag 'favicon.ico'
  = stylesheet_link_tag    'session', media: 'all'
  = javascript_include_tag 'session'

  meta{name='viewport', content='width=device-width, initial-scale=1, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no'}

  = csrf_meta_tags

  body
    .site
      .content
        .container
          = yield
      .footer
        = render 'layouts/footer'

app/views/preview/home/index.html.slim
.jumbotron
  h1 Herman Zvonimir Došilović

.social
  .social-group
    = iconfont_linkedin link: 'https://www.linkedin.com/in/hermanzdosilovic', round: true, input_html: { target: '_blank' }
    = iconfont_facebook link: 'https://www.facebook.com/profile.php?id=1203852653', round: true, input_html: { target: '_blank' }
  .social-group
    = iconfont_github link: 'https://github.com/hermanzdosilovic', round: true, input_html: { target: '_blank' }
    = iconfont_bitbucket link: 'https://bitbucket.org/hermanzdosilovic/', round: true, input_html: { target: '_blank' }
  .social-group
    = iconfont_mail link: 'mailto:hermanz.dosilovic@gmail.com', round: true
    = iconfont_document link: 'https://dl.dropboxusercontent.com/u/96682413/Herman_Zvonimir_Dosilovic_Resume.pdf', round: true, input_html: { target: '_blank' }

.jumbotron
  p Site is under construction

app/views/shared/_modal.html.slim
.modal.fade
  .modal-dialog
    .modal-content
      .modal-header.clearfix
        button.close data-dismiss="modal"
          |&times;
        h4 Header
      .modal-body.clearfix

app/views/users/_delete_account_body.html.slim
= simple_form_for(@user, url: registration_path(@user), method: :delete, remote: true) do |f|
  = f.input :password, autofocus: true, label: "Password (#{link_to('Forgot your password?', new_user_password_path)})".html_safe
  = f.button :submit, 'Confirm password', class: 'btn-primary'